services:
  db:
    image: mysql:8.4.0
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: "$DATABASE_NAME"
      MYSQL_USER: "$DATABASE_USER"
      MYSQL_PASSWORD: "$DATABASE_PASSWORD"
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - db
    volumes:
      - ./src:/app/src

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
